### PR TITLE
Add badges and travis and coveralls

### PR DESCRIPTION
**Pull request by adrianmoisey**
I LOVE BADGES!

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by adrianmoisey** [comment]
:bell:

**Comment by zoidbergwill** [comment]
:+1:

**Pull request merged**
