### PR TITLE
Bump version to 0.0.7 for release

### PR DESCRIPTION
**Pull request by alexmojaki**
In general do I need approval to merge such requests?

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by jouberthenk** [comment]
You should add a changelog entry to describe what's contained in this release.

Generally the only approval you need is a :+1: from someone at yola.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by alexmojaki** [comment]
@jouberthenk :+1: ?

**Comment by jouberthenk** [comment]
:+1: 

So usually you don't need to @mention specific people to review your stuff unless you need their expertise. As long as the project is linted (has a .lintrc), snitch will chime in with warnings or :sparkles: which means participants will get a notification that something has changed in the pull and they can look again. If you feel something is being ignored for too long (or if the project doesn't have snitch), you can leave comment with :bell: in it to re notify participants.

**Comment by jouberthenk** [comment]
also add a tag https://github.com/yola/healthcheck/tags

**Comment by alexmojaki** [comment]
I don't know how

**Comment by adrianmoisey** [comment]
https://github.com/yola/healthcheck/releases -> Draft a new release

**Comment by alexmojaki** [comment]
Am I supposed to give it an actual title or attach files?

**Comment by jouberthenk** [comment]
You could model it on the last release: https://github.com/yola/healthcheck/releases/tag/0.0.4

**Comment by adrianmoisey** [comment]
^^^ what Henk said. Not worries about any attached file.

**Comment by alexmojaki** [comment]
But I can't actually tell if the big 0.0.4 is a title or just generated from the tag version.

**Comment by adrianmoisey** [comment]
I think it's the title

**Comment by alexmojaki** [comment]
And I wasn't sure if github attached those files or a person, although I guess @adrianmoisey covered that.

**Comment by adrianmoisey** [comment]
See https://github.com/yola/yoaudit/releases

**Comment by alexmojaki** [comment]
It's a really great title

**Comment by adrianmoisey** [comment]
Literally the best

**Comment by stefanor** [comment]
> In general do I need approval to merge such requests?

What's the point of a pull request, if nobody is going to review it. So, yes, if you're opening a pull request, it's so that you can get review.

> https://github.com/yola/healthcheck/releases -> Draft a new release

or just tag with `git tag`, and push the tag with a `push --tags`

**Comment by adrianmoisey** [comment]
> What's the point of a pull request, if nobody is going to review it. So, yes, if you're opening a pull request, it's so that you can get review.

Unless it's a PR from `master` into `release`

**Comment by alexmojaki** [comment]
@stefanor my understanding from the Git Etiquette page was that *everything* must be done in a pull request, never a push to master, but that in some cases (e.g. the master -> release example that Adrian gave) it's just to leave a paper trail. That's why I was checking.

**Comment by stefanor** [comment]
That's the only "some case" I can think of.

We used to also do library releases (like this PR) without a PR, as there wasn't much to review. (And a whole bunch of release-related stuff has to be done by hand, without review, anyway. And GitHub had no UI for creating tags). But that's pretty frowned on these days...

**Pull request merged**
