### PR TITLE
Update healthcheck version

### PR DESCRIPTION
**Pull request by ekoval**
Update healthcheck version
#10

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by ekoval** [comment]
Self-ShipIt, because the change is very minor.

**Comment by adrianmoisey** [comment]
Why was the original change reverted? You should do a rebase and clean up git history before pushing to github.

**Comment by ekoval** [comment]
First I mistakenly committed changes to master, so I rolled back that commit.

**Comment by adrianmoisey** [comment]
> First I mistakenly committed changes to master, so I rolled back that commit.

`git rebase -i` is your friend :smile:

**Comment by ekoval** [comment]
Done. That's nice experience for me (was doing rebase second time in my life), but I'm not sure I should have done it for this particular case. Only one commit, almost "dead" repo...

**Comment by adrianmoisey** [comment]
> I'm not sure I should have done it for this particular case

Should have waited for a review before merging then :wink:

**Comment by zoidbergwill** [comment]
Not really one commit, two commits that are completely unnecessary. Since they basically cancel each other out.

Also, how is this repo "dead"?

**Comment by ekoval** [comment]
I said "almost "dead"".
I mean not too much activity happens there. My point is that this rebase probably wasn't worth efforts.

**Pull request merged**
